import type { NextPage } from 'next'
import Head from 'next/head'
import { useAuth } from '@m3o/nextjs'

const Home: NextPage = () => {
  const { login, logout, user } = useAuth()

  return (
    <div>
      <Head>
        <title>Test M3O Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ? user.email : <p>Loading...</p>}
      <button
        onClick={() =>
          login({ email: 'martin@m3o.com', password: 'incorrect' })
        }
      >
        Login
      </button>
      <button onClick={() => logout()}>Logout</button>
    </div>
  )
}

export default Home
