import type { NextPage } from 'next'
import Head from 'next/head'
import { useUser, useEmailLogin, useLogout } from '@m3o/nextjs'
import { Layout } from '../components/Layout'

const Home: NextPage = () => {
  const { user } = useUser()
  const { login } = useEmailLogin()
  const { logout } = useLogout()

  return (
    <>
      <Head>
        <title>Test M3O Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="container">
          {user && <p data-testid="logged-in-email">{user.email}</p>}
        </div>
      </Layout>
    </>
  )
}

export default Home
