import type { NextPage, NextPageContext, GetServerSideProps } from 'next'
import Head from 'next/head'
import { withAuth } from '@/m3o/server'

export const getServerSideProps = withAuth(async context => {
  if (!context.req.user) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props: {},
  }
})

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Test M3O Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Private
    </div>
  )
}

export default Home
